name: ci

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun tsc
      - run: bun prepublishOnly && bunx pkg-pr-new publish --comment=off
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with: { prefix: "v" }
      - if: steps.version.outputs.is_valid == 'true'
        run: |
          bun bump ${GITHUB_REF#refs/tags/v}
          npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_AUTH_TOKEN}}
      - if: steps.version.outputs.is_valid == 'true' && !steps.version.outputs.prerelease
        run: npm publish --access public
      - if: steps.version.outputs.prerelease
        run: npm publish --tag preview